### ISSUE TITLE
Make it work with webpack dev server

### ISSUE THREAD

**Issue by prateekbh** [prateekbh/babel-esm-plugin#12]
Make this work with webpack dev server as requested in  https://github.com/developit/preact-cli/issues/721

**Comment by prateekbh** [comment]
Hah! looks like there's nothing to do here, it already works fine

**Comment by fvonellerts** [comment]
If anyone stranding here wants to make this plugin work with `html-webpack-plugin`, add this line to your .html file:
```html
<script src="<%=webpackConfig.output.publicPath%>js/index.module.js" type="module"></script>
```
and use `script-ext-html-webpack-plugin` to inject nomodule into the regular output:
```javascript
new ScriptExtHtmlWebpackPlugin({
        custom: {
            test: /(?<!\.module)\.js$/,
            attribute: 'nomodule',
            value: ''
        }
    })
```

Using `html-webpack-harddisk-plugin` this will even work with HMR.
