### ISSUE TITLE
Different hash

### ISSUE THREAD

**Issue by fvonellerts** [prateekbh/babel-esm-plugin#15]
Hi prateekbh

First of all, thank you for this great plugin! A nice way to ship less code.

However, I just encountered a bug: The filename `[hash]` and `[chunkhash]` don't match those used otherwise by Webpack - this makes cache busting impossible when not using the HTML plugin.

Best regards,
Fabian von Ellerts

**Comment by prateekbh** [comment]
Hi! Thanks for the kind words 😊

Just trying to understand the problem, are you saying that the `[hash]/[chunkhash]` are not the same as the files generated by webpack without the plugin?

**Comment by fvonellerts** [comment]
Hi, no problem :)

That was fast!
Yes exactly. I am using [hash-webpack-plugin](https://github.com/xpepermint/hash-webpack-plugin) to extract the webpack `[hash]` and insert it into our server application for cache busting. Because `babel-esm-plugin` uses a different hash for it's files, I can't use this technique for the `type="module"` scripts.

**Comment by prateekbh** [comment]
So IIUC `[hash]` is dependent on the content of the file. since the code in your ES5 and ES6 files is different thus the `[hash]` is expected to be different as well.
the only action item on us (if any) would be to check with your specified plugin and see if can yield the hash from child compiler as well

**Comment by fvonellerts** [comment]
According to [this medium.com article](https://medium.com/@sahilkkrazy/hash-vs-chunkhash-vs-contenthash-e94d38a32208), the `[hash]` is based on the build:

Hash:
Hash is corresponding to build. Each chunk will get same hash across the build. If anything change in your build, corresponding hash will also change.

Chunkhash:
Chunkhash is based on webpack entry point Each entry defined will have it’s own hash. If anything changes for that particular entry point than only corresponding hash will change.

To my understanding babel-esm-plugin runs on the same build, so it's chunks should have the same build hash.

**Comment by prateekbh** [comment]
Ahh i see it.
No so esm run a child compilation of its own so thats why it might have a different hash value.

I can definitely look this up on how to get this consistent

**Comment by prateekbh** [comment]
yeah sorry i tried. every compilation is having its own `hash` and seems to be readOnly so i cant just use parent compilation hash

**Comment by prateekbh** [comment]
webpack ppl tell me that this might be possible... now looking into this again

**Comment by fvonellerts** [comment]
@prateekbh Thanks for your effort in trying to fix this! If it's really not possible, it would be great to make the hash somehow reachable (like `stats.hash` or as a callback in the `BabelEsmPlugin` object).

**Comment by fvonellerts** [comment]
I'm sorry but the fix did not work for me:
![Bildschirmfoto 2019-09-30 um 16 20 12](https://user-images.githubusercontent.com/10993125/65887971-17cb1080-e39f-11e9-8414-fd94ebf81343.png)

I'm using babel-esm-plugin v0.6.1 and webpack v4.35.2:
```javascript
new BabelEsmPlugin({
        filename: 'js/[name]_[hash].module.js',
        chunkFilename: 'js/[name]_[chunkhash].dyn.module.js'
    })
...
output: {
        filename: 'js/[name]_[hash].js',
        chunkFilename: 'js/[name]_[chunkhash].dyn.js'
    },
```

**Comment by prateekbh** [comment]
Cool, given that we have a test for it it'd be great if u can create a minimal repo for this bug
