### ISSUE TITLE
Switch dependencies and devDependencies

### ISSUE THREAD

**Issue by jgierer12** [prateekbh/babel-esm-plugin#16]
It seems like your `dependencies` and `devDependencies` are the wrong way around. `ava` and `webpack` should definitely be devDependencies since they're only used during development/testing. `chalk`, `babel-loader` and their peerDependencies should be normal dependencies since they are used in the production build. `release-it`, `webpack-cli` and `deepcopy` seen to be correct.

The reason I bring this up is because I'm using Yarn PnP, which is very strict about correct dependency declaration. If a package `require`s another package without it being listed in the (non-dev) `dependencies`, it will throw an error which is currently the case.

**Comment by prateekbh** [comment]
lol so sorry about this, do you mind opening a PR?
