### ISSUE TITLE
Built in webpack modes have no effect

### ISSUE THREAD

**Issue by prateekbh** [prateekbh/babel-esm-plugin#2]
While default bundles are auto minified by `webpack --mode=production`. Files generated by this are not.

Also `webpack --mode=development` have no effect on output

**Comment by prateekbh** [comment]
Ummm I haven't tried that

**Comment by ev1stensberg** [comment]
Just trying to triage and see if the bug is on us

**Comment by prateekbh** [comment]
Actually even running just webpack defaults to production mode right?

I don't think its a thing with flag or config its just childCompiler is skipping something

**Comment by prateekbh** [comment]
@ev1stensberg I tried adding

```
 childCompiler.options.plugins.push(new UglifyJsPlugin());
```

after: https://github.com/prateekbh/babel-esm-plugin/blob/master/src/index.js#L18

still doesn't minify... any idea why?

**Comment by prateekbh** [comment]
Apparently this was due to the effect that I changed extension from .just to .mjs

Fixed it by keeping default file names as blah.es6.js
