### ISSUE TITLE
Does not work with vue-loader?

### ISSUE THREAD

**Issue by wzc0x0** [prateekbh/babel-esm-plugin#23]
config like this : 

```javascript
 module: {
      rules: [{
                test: /\.vue$/,
                loader: "vue-loader"
            },
            {
                test: /\.js$/,
                exclude: /(node_modules|bower_components)/,
                use: {
                    loader: "babel-loader",
                    options: {
                        presets: [
                            [
                                "@babel/preset-env",
                                {
                                    targets: {
                                        browsers: ["last 2 versions", "safari >= 7"]
                                    }
                                }
                            ]
                        ]
                    }
                }
            },
            ...
        ]
 },
 plugins: [
  new VueLoaderPlugin(),
  new BabelEsmPlugin()
],
```
some errors: 

```
UnhandledPromiseRejectionWarning: Error: [VueLoaderPlugin Error] No matching use for vue-loader is found.
Make sure the rule matching .vue files include vue-loader in its use.
    at VueLoaderPlugin.apply (/Users/wzc0x0/Desktop/MySpace/webpack-boilerplate/node_modules/vue-loader/lib/plugin.js:65:13
)
    at compiler.hooks.make.tapAsync (/Users/wzc0x0/Desktop/MySpace/webpack-boilerplate/node_modules/babel-esm-plugin/src/in
dex.js:66:18)
```

**Comment by prateekbh** [comment]
well it basically works with babel-loader. Are you not using babel along with vue-loader?

**Comment by wzc0x0** [comment]
I'm sure use babel-loader. But may be in conflict with the `VueLoaderPlugin`. when I remove the `BabelEsmPlugin ` no error everything is ok!

**Comment by wzc0x0** [comment]
Here is my respository link, you can run `npm run test` and show this erros
https://github.com/wzc0x0/webpack-boilerplate

**Comment by wzc0x0** [comment]
see more
https://github.com/DanielSchaffer/webpack-babel-multi-target-plugin

**Comment by prateekbh** [comment]
Hi!
Sorry for the late reply.

I was able to make it work for your repo with the following code:

```js
new BabelEsmPlugin({
  filename: 'static/js/[name].[contenthash].mjs',
  chunkFilename: 'static/js/[name].[contenthash].mjs',
  excludedPlugins: ['VueLoaderPlugin', 'BabelEsmPlugin']
})
```

Output:
<img width="675" alt="Screen Shot 2019-07-10 at 5 15 43 PM" src="https://user-images.githubusercontent.com/5960497/61013156-5fa94100-a336-11e9-98df-71eca16e8ed9.png">

**Comment by wzc0x0** [comment]
OH! Very Well ! Thanks a lot! 😁

**Comment by wzc0x0** [comment]
https://github.com/prateekbh/babel-esm-plugin/blob/44fcfceb3232e532d88498d99780ceb09619b140/src/index.js#L16-L25  

Here is a small problem:
`Object.assign` function should replace the `options.excludedPlugins` array with `excludedPlugins`, Not merge the options.

**Comment by prateekbh** [comment]
for tracking purpose, can you open a separate issue for this?
