### ISSUE TITLE
Doesn't seem to exclude externals from bundle

### ISSUE THREAD

**Issue by glebcha** [prateekbh/babel-esm-plugin#25]
I use https://github.com/liady/webpack-node-externals to handle externals and cjs is ok, but esm include all of external dependencies.
Maybe I did something wrong?

**Comment by prateekbh** [comment]
Can u give us a sample repo?
It'll be extremely helpful

**Comment by glebcha** [comment]
Looks like https://github.com/webpack-contrib/worker-loader/issues/95 related

**Comment by prateekbh** [comment]
oh yes that absolutely seems to be the root cause. I'll try to fix this.

**Disclaimer:** My free time during the pandemic is running seriously low. PRs are always welcome and will be reviewed at priority

**Comment by fabioricali** [comment]
could there be a workaround for this issue?

**Comment by prateekbh** [comment]
Adding the externalPlugin to this source code would be fix i guess

**Comment by prograhammer** [comment]
Yeah, the quick fix is (in `src/index.js` of this plugin):

```js
const { ExternalsPlugin } = require('webpack');

// ....

      if (compiler.options.externals) {
        new ExternalsPlugin('module', compiler.options.externals).apply(childCompiler);
      }
```
