### ISSUE TITLE
Make it work with webpack 3.x

### ISSUE THREAD

**Issue by prateekbh** [prateekbh/babel-esm-plugin#3]
Currently only works with webpack 4.x. 
Check if this can work with webpack 3.x

**Comment by ev1stensberg** [comment]
Mode is not supported in v3, so that might be harder. Also, the CSS plugins and chunk splits have changed in v4

**Comment by prateekbh** [comment]
This is just creating a childCompiler and running it with a separate babel config. I am pretty sure `mode` is not a requirement for this to run. 

Its just implementation on hook vs tappable I guess.

**Comment by ev1stensberg** [comment]
That's true. Keep in mind v4 does uglify and optimizations by default when the mode is set to prod
