### ISSUE TITLE
Automatically switch Terser/Uglify to ecma:8 input & output

### ISSUE THREAD

**Issue by developit** [prateekbh/babel-esm-plugin#35]
The child compiler spawned by `babel-preset-modules` needs to change Terser's parsing and output modes to `ecma:8` in order to preserve arrow functions and other constructs, and to allow it to minify modern syntax effectively.

**Comment by developit** [comment]
@prateekbh I have an implementation now that I will PR ASAP.

**Comment by prateekbh** [comment]
Thanks i'll publish it ASAP after merging

**Comment by fengzilong** [comment]
I would like to send a PR for this issue, but I was stuck with a question

If I use `terser-webpack-plugin` in this way

`webpack.config.js`
```js
{
  optimization: {
    minimizer: [
      {
        apply( compiler ) {
          const TerserPlugin = require( 'terser-webpack-plugin' )
          new TerserPlugin( {
            terserOptions: { output: { ecma: 5 } }
          } ).apply( compiler )
        }
      }
    ]
  }
}
```

Like [what webpack defaults.js did](https://github.com/webpack/webpack/blob/f0b1a71d5a4ba7a685e76d08281195364d7dd9b3/lib/config/defaults.js#L475-L481)

I can't access terser instance with `parentCompiler.options.optimization.minimizer` anymore

Any advice please? for how to access and modify the terserOptions in this case @prateekbh @developit

**Comment by prateekbh** [comment]
Sadly we lately realized that doing this wouldn't really make much of a difference in the output.

Not really worth putting much efforts in
