### ISSUE TITLE
Peer dependency of fixed webpack version

### ISSUE THREAD

**Issue by martinbroos** [prateekbh/babel-esm-plugin#43]
Hi,

Interesting plugin which I like to try out. But i'm facing the issue that an old version of webpack is required as a peer dependency.

Is there a reason why you required version 4.28.4 of webpack ?

**Comment by prateekbh** [comment]
oh no, not really. any version of webpack v4 should do

**Comment by martinbroos** [comment]
See PR: https://github.com/prateekbh/babel-esm-plugin/pull/44
