### ISSUE TITLE
child compiler's assets does not have `webpackJsonpCallback` function

### ISSUE THREAD

**Issue by prateekbh** [prateekbh/babel-esm-plugin#5]
Any assets created by `babel-esm-plugin` does not have `webpackJsonpCallback` to load the respective chucks.

**Comment by prateekbh** [comment]
@ev1stensberg @developit any ideas?

**Comment by ev1stensberg** [comment]
I don't really know to be honest. @TheLarkInn might have some input on that.

**Comment by prateekbh** [comment]
I fixed this by adding https://github.com/prateekbh/babel-esm-plugin/blob/master/src/index.js#L40
