### ISSUE TITLE
Got a question around asyncTap

### ISSUE THREAD

**Issue by ScriptedAlchemy** [prateekbh/babel-esm-plugin#6]
Yo dude. I came across your comments on GitHub. Were you able to solve the issue you had? It was around needing a tapAsyc. Pretty much I’ve got the same problem where this.hooks.thisCompilation.tap throws an error because tap is undefined.

**Comment by prateekbh** [comment]
Can you point me around the comment? I have a super poor memory and am in middle of couple of things. sorry for the trouble.
